/**
 * Typed Env interface for the remote-agents Worker.
 *
 * Extends the global `Env` interface (generated by `wrangler types` into
 * `worker-configuration.d.ts`) with the Worker secrets that come from
 * `.dev.vars` (local) or `wrangler secret put` (production).
 *
 * All secrets are injected at runtime — never baked into the Docker image
 * or committed to git.
 *
 * To add a new secret:
 *   1. Add it to the `WorkerSecrets` interface below.
 *   2. Document it in `.dev.vars.example`.
 *   3. Run `wrangler secret put <NAME>` for production.
 *   4. Add it to `getContainerEnv()` in `src/secrets.ts` if containers need it.
 */

/**
 * The Worker secrets injected via `.dev.vars` or `wrangler secret put`.
 *
 * These are merged into the global `Env` interface so any file that uses
 * `env: Env` gets full type-safety without any extra imports.
 */
export interface WorkerSecrets {
  // ── LLM provider ───────────────────────────────────────────────────────────
  /**
   * Anthropic API key used by the orchestrator to call Claude and passed
   * into every container so `opencode serve` can make LLM API calls.
   *
   * Obtain: https://console.anthropic.com/settings/keys
   * Format: sk-ant-...
   * Wrangler: `wrangler secret put ANTHROPIC_API_KEY`
   */
  ANTHROPIC_API_KEY: string;

  // ── GitHub ──────────────────────────────────────────────────────────────────
  /**
   * GitHub personal access token (classic PAT or fine-grained PAT).
   * Passed into containers so `gh` can push branches and open pull requests.
   *
   * Classic PAT scopes: repo, workflow
   * Fine-grained PAT permissions: Contents (rw), Pull requests (rw), Workflows (rw)
   *
   * Obtain: https://github.com/settings/tokens
   * Format: ghp_... (classic) or github_pat_... (fine-grained)
   * Wrangler: `wrangler secret put GH_TOKEN`
   */
  GH_TOKEN: string;

  // ── Linear / lb ─────────────────────────────────────────────────────────────
  /**
   * Linear API key used by `lb` inside containers to sync issue state,
   * update statuses, and create/read issues.
   *
   * Obtain: https://linear.app/settings/api  →  "Personal API keys"
   * Format: lin_api_...
   * Wrangler: `wrangler secret put LINEAR_API_KEY`
   */
  LINEAR_API_KEY: string;

  // ── Git identity ─────────────────────────────────────────────────────────────
  /**
   * Display name used for git commits made by remote agents.
   * Passed to `git config user.name` inside the container.
   *
   * Example: "Remote Agent"
   * Wrangler: `wrangler secret put GIT_AUTHOR_NAME`
   */
  GIT_AUTHOR_NAME: string;

  /**
   * Email address used for git commits made by remote agents.
   * Passed to `git config user.email` inside the container.
   *
   * Example: "agent@example.com"
   * Wrangler: `wrangler secret put GIT_AUTHOR_EMAIL`
   */
  GIT_AUTHOR_EMAIL: string;
}

/**
 * Merge `WorkerSecrets` into the global `Env` interface.
 *
 * `worker-configuration.d.ts` (generated by `wrangler types`) declares:
 *   interface Env extends Cloudflare.Env {}
 *
 * TypeScript merges all ambient `interface Env` declarations, so adding our
 * secrets here makes them available on every `env: Env` parameter project-wide.
 */
declare global {
  // eslint-disable-next-line @typescript-eslint/no-empty-object-type
  interface Env extends WorkerSecrets {}
}
