/**
 * Worker entrypoint for the remote-agents system.
 *
 * Routes requests to the appropriate Durable Object:
 * - Orchestrator (AIChatAgent) — chat + agent management
 * - Sandbox — container lifecycle (managed by orchestrator tools)
 *
 * The `routeAgentRequest` function from the agents SDK handles
 * WebSocket upgrades and routing to the correct DO instance.
 *
 * Static routes:
 * - GET /            → dashboard UI (pre-built React app)
 * - GET /dashboard   → dashboard UI
 * - GET /health      → health check JSON
 */
import { routeAgentRequest } from 'agents';
import { assertRequiredSecrets } from './secrets.js';

// Pre-built dashboard HTML (built by scripts/build-dashboard.mjs before wrangler runs).
// Wrangler imports this as a text module via the "rules" config in wrangler.jsonc.
// The module type is declared in worker-configuration.d.ts (generated by `wrangler types`).
import dashboardHtml from '../public/dashboard.html';

// Re-export Durable Object classes so wrangler can find them
export { Sandbox } from '@cloudflare/sandbox';
export { Orchestrator } from './orchestrator.js';

// Import env types
import './env.js';

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    // Fail fast if required secrets are missing
    assertRequiredSecrets(env);

    const url = new URL(request.url);

    // Serve the dashboard at / and /dashboard
    if (
      request.method === 'GET' &&
      (url.pathname === '/' || url.pathname === '/dashboard')
    ) {
      return new Response(dashboardHtml as string, {
        headers: { 'Content-Type': 'text/html; charset=utf-8' },
      });
    }

    // Health check
    if (url.pathname === '/health') {
      return Response.json({ status: 'ok', timestamp: new Date().toISOString() });
    }

    // routeAgentRequest handles:
    //   /agents/Orchestrator/:name  → Orchestrator DO (chat WebSocket)
    //   /agents/Sandbox/:name       → Sandbox DO
    // Returns null for non-agent routes.
    const agentResponse = await routeAgentRequest(request, env);
    if (agentResponse) return agentResponse;

    // 404 for anything else
    return new Response('Not found', { status: 404 });
  },
};
